redmine-plugins/redmine_people/config/routes.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2024 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
  collection do
    get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
    get :autocomplete_for_person
    post :bulk_edit, :bulk_update, :send_mails, :add_manager
    delete :bulk_destroy
    get 'calendar' => 'people_calendars#index'
    resources :holidays, except: :show, controller: :people_holidays, as: :people_holidays
  end

  member do
    get :manager
    get :autocomplete_for_manager
    delete :destroy_avatar
    get 'tabs/:tab' => 'people#show', :as => 'tabs'
    get 'load_tab' => 'people#load_tab', :as => 'load_tab'
    delete 'remove_subordinate' => 'people#remove_subordinate', :as => 'remove_subordinate'
  end
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
    get 'tabs/:tab' => 'departments#show', :as => 'tabs'
    get 'load_tab' => 'departments#load_tab', :as => 'load_tab'
  end

  get :org_chart, on: :collection
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries, except: [:index]

constraints object_type: /(departments)/ do
  get 'attachments/:object_type/:object_id/edit', to: 'attachments#edit_all', as: 'departments_attachments_edit'
  patch 'attachments/:object_type/:object_id', to: 'attachments#update_all', as: 'departments_attachments'
  get 'attachments/:object_type/:object_id/download', to: 'attachments#download_all', as: 'departments_attachments_download'
end

redmine-plugins/redmine_people/app/views/common/_department_tabs.html.erb
<% selected_tab = params[:tab] ? params[:tab].to_s : tabs.first[:name] %>

<div class="tabs">
  <ul>
    <% tabs.each do |tab| -%>
        <li><%= link_to tab[:label], tabs_department_path(@department, :tab => tab[:name]),
                        :id => "tab-#{tab[:name]}",
                        :class => (tab[:name] != selected_tab ? 'tab-header' : 'selected tab-header'),
                        :data => { :name => tab[:name], :partial => tab[:partial]},
                        :onclick => "showPeopleTab('#{tab[:name]}'); this.blur(); return false;" %></li>
    <% end -%>
  </ul>
  <div class="tabs-buttons" style="display:none;">
    <button class="tab-left" onclick="moveTabLeft(this);"></button>
    <button class="tab-right" onclick="moveTabRight(this);"></button>
  </div>
</div>

<% tabs.each do |tab| %>
    <% selected = tab[:name] == selected_tab %>
    <div class="tab-placeholder tab-content <%= 'active loaded' if selected %>" id="tab-placeholder-<%= tab[:name] %>" style="<%= "display: block" if selected %>">
      <%= render(:partial => tab[:partial]) if selected %>
    </div>
<% end %>
<script type='text/javascript'>
  $(document).ready(displayTabsButtons);
  $(window).resize(displayTabsButtons);
  $(document).ready(function(){ setupDeferredTabs('<%= load_tab_department_path(@department) %>') });
</script>

redmine-plugins/redmine_people/app/views/common/_layout_bottom.html.erb
<%= render :partial => 'common/people_select2_data' %>

redmine-plugins/redmine_people/app/views/common/_people_select2_data.html.erb
<%= transform_to_select2 'people', format_state: 'formatStateWithAvatar', min_input_length: 1, url: autocomplete_for_manager_person_path(id: 'new') %>

redmine-plugins/redmine_people/app/views/common/_people_tabs.html.erb
<% selected_tab = params[:tab] ? params[:tab].to_s : tabs.first[:name] %>

<div class="tabs">
  <ul>
    <% tabs.each do |tab| -%>
        <li><%= link_to tab[:label], tabs_person_path(@person, :tab => tab[:name]),
                        :id => "tab-#{tab[:name]}",
                        :class => (tab[:name] != selected_tab ? 'tab-header' : 'selected tab-header'),
                        :data => { :name => tab[:name], :partial => tab[:partial]},
                        :onclick => "showPeopleTab('#{tab[:name]}'); this.blur(); return false;" %></li>
    <% end -%>
  </ul>
  <div class="tabs-buttons" style="display:none;">
    <button class="tab-left" onclick="moveTabLeft(this);"></button>
    <button class="tab-right" onclick="moveTabRight(this);"></button>
  </div>
</div>
<% tabs.each do |tab| %>
    <% selected = tab[:name] == selected_tab %>
    <div class="tab-placeholder tab-content <%= 'active loaded' if selected %>" id="tab-placeholder-<%= tab[:name] %>" style="<%= "display: block" if selected %>">
      <%= render(:partial => tab[:partial]) if selected %>
    </div>
<% end %>
<script type='text/javascript'>
  $(document).ready(displayTabsButtons);
  $(window).resize(displayTabsButtons);
  $(document).ready(function(){ setupDeferredTabs('<%= load_tab_person_path(@person) %>') });
</script>