redmine-plugins/redmine_dmsf/config/routes.rb
# frozen_string_literal: true

# Redmine plugin for Document Management System "Features"
#
#  Vít Jonáš <vit.jonas@gmail.com>, Daniel Munn <dan.munn@munnster.co.uk>, Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

if Redmine::Plugin.installed? 'redmine_dmsf'
  RedmineApp::Application.routes.draw do
    #
    # dmsf controller
    #   /projects/<project>/dmsf
    #   [As this controller also processes 'folders' it maybe better to branch into a folder route rather than leaving
    #    it as is]
    ##
    post '/projects/:id/dmsf/create', controller: 'dmsf', action: 'create'
    get '/projects/:id/dmsf/notify/activate', controller: 'dmsf', action: 'notify_activate', as: 'notify_activate_dmsf'
    get '/projects/:id/dmsf/notify/deactivate', controller: 'dmsf',
                                                action: 'notify_deactivate',
                                                as: 'notify_deactivate_dmsf'
    delete '/projects/:id/dmsf/delete', controller: 'dmsf', action: 'delete', as: 'delete_dmsf'
    post '/projects/:id/dmsf/save', controller: 'dmsf', action: 'save'
    post '/projects/:id/dmsf/save/root', controller: 'dmsf', action: 'save_root'
    post '/projects/:id/dmsf/entries', controller: 'dmsf', action: 'entries_operation', as: 'entries_operations_dmsf'
    post '/projects/:id/dmsf/entries/delete', controller: 'dmsf', action: 'delete_entries', as: 'delete_entries'
    post '/projects/:id/dmsf/entries/email', to: 'dmsf#entries_email', as: 'email_entries'
    get '/projects/:id/dmsf/entries/download_email_entries', controller: 'dmsf',
                                                             action: 'download_email_entries',
                                                             as: 'download_email_entries'
    get '/projects/:id/entries/copymove', to: 'dmsf#copymove', as: 'copymove_entries'
    get '/projects/:id/dmsf/lock', controller: 'dmsf', action: 'lock', as: 'lock_dmsf'
    get '/projects/:id/dmsf/unlock', controller: 'dmsf', action: 'unlock', as: 'unlock_dmsf'
    get '/projects/:id/dmsf/', controller: 'dmsf', action: 'show', as: 'dmsf_folder'
    get '/projects/:id/dmsf/new', controller: 'dmsf', action: 'new', as: 'new_dmsf'
    get '/projects/:id/dmsf/edit', controller: 'dmsf', action: 'edit', as: 'edit_dmsf'
    get '/projects/:id/dmsf/edit/root', controller: 'dmsf', action: 'edit_root', as: 'edit_root_dmsf'
    get '/projects/:id/dmsf/trash', controller: 'dmsf', action: 'trash', as: 'trash_dmsf'
    get '/projects/:id/dmsf/restore', controller: 'dmsf', action: 'restore', as: 'restore_dmsf'
    post '/projects/dmsf/expand_folder', controller: 'dmsf', action: 'expand_folder', as: 'expand_folder_dmsf'
    get '/projects/dmsf/add_email', to: 'dmsf#add_email', as: 'add_email_dmsf'
    post '/projects/dmsf/append_email', to: 'dmsf#append_email', as: 'append_email_dmsf'
    get '/projects/dmsf/autocomplete_for_user', to: 'dmsf#autocomplete_for_user'
    put '/projects/:id/dmsf', controller: 'dmsf', action: 'drop'
    get '/projects/:id/dmsf/empty_trash', to: 'dmsf#empty_trash', as: 'empty_trash'
    get '/dmsf', to: 'dmsf#index', as: 'dmsf_index'
    get '/dmsf/digest', to: 'dmsf#digest', as: 'dmsf_digest'
    post '/dmsf/digest', to: 'dmsf#reset_digest', as: 'dmsf_reset_digest'

    # dmsf_context_menu_controller
    match '/projects/dmsf/context_menu', to: 'dmsf_context_menus#dmsf', as: 'dmsf_context_menu', via: %i[get post]
    match '/projects/:id/dmsf/trash/context_menu', to: 'dmsf_context_menus#trash',
                                                   as: 'dmsf_trash_context_menu',
                                                   via: %i[get post]

    #
    # dmsf_state controller
    #   /projects/<project>/dmsf/state
    ##
    post '/projects/:id/dmsf/state', controller: 'dmsf_state', action: 'user_pref_save', as: 'dmsf_user_pref_save'

    #
    #  dmsf_upload controller
    #   /projects/<project>/dmsf/upload - dmsf_upload controller
    ##

    get '/projects/:id/dmsf/upload/multi_upload', controller: 'dmsf_upload',
                                                  action: 'multi_upload',
                                                  as: 'multi_dmsf_upload'
    post '/projects/:id/dmsf/upload/files', controller: 'dmsf_upload', action: 'upload_files'
    get '/projects/:id/dmsf/upload/files', controller: 'dmsf_upload', action: 'upload_files'
    post '/projects/:id/dmsf/upload', controller: 'dmsf_upload', action: 'upload'
    post '/projects/:id/dmsf/upload/commit', controller: 'dmsf_upload', action: 'commit_files'
    post '/projects/:id/dmsf/commit', controller: 'dmsf_upload', action: 'commit'
    post 'dmsf_uploads', to: 'dmsf_upload#upload'
    delete '/dmsf/attachments/:id/delete', to: 'dmsf_upload#delete_dmsf_attachment', as: 'dmsf_attachment'
    delete '/dmsf/link_attachments/:id/delete', to: 'dmsf_upload#delete_dmsf_link_attachment',
                                                as: 'dmsf_link_attachment'

    #
    # dmsf_links controller
    #   /dmsf/links/<file id>
    ##
    get '/dmsf/links/:id/restore', controller: 'dmsf_links', action: 'restore', as: 'restore_dmsf_link'
    delete '/dmsf/links/:id', controller: 'dmsf_links', action: 'delete'

    # Just to keep backward compatibility with old external direct links
    get '/dmsf_files/:id', controller: 'dmsf_files', action: 'show'
    get '/dmsf_files/:id/download', controller: 'dmsf_files', action: 'show', download: ''

    #
    # dmsf_files controller
    #   /dmsf/files/<file id>
    ##
    get '/dmsf/files/:id/notify/activate', controller: 'dmsf_files',
                                           action: 'notify_activate',
                                           as: 'notify_activate_dmsf_files'
    get '/dmsf/files/:id/notify/deactivate', controller: 'dmsf_files',
                                             action: 'notify_deactivate',
                                             as: 'notify_deactivate_dmsf_files'
    get '/dmsf/files/:id/lock', controller: 'dmsf_files', action: 'lock', as: 'lock_dmsf_files'
    get '/dmsf/files/:id/unlock', controller: 'dmsf_files', action: 'unlock', as: 'unlock_dmsf_files'
    post '/dmsf/files/:id/delete', controller: 'dmsf_files', action: 'delete', as: 'delete_dmsf_files'
    post '/dmsf/files/:id/revision/create', controller: 'dmsf_files', action: 'create_revision'
    get '/dmsf/files/:id/revision/delete', controller: 'dmsf_files', action: 'delete_revision', as: 'delete_revision'
    get '/dmsf/files/:id/revision/obsolete', controller: 'dmsf_files',
                                             action: 'obsolete_revision',
                                             as: 'obsolete_revision'
    get '/dmsf/files/:id/download', to: 'dmsf_files#view',
                                    download: '',
                                    as: 'download_dmsf_file' # Otherwise will not route nil into the download param
    get '/dmsf/files/:id/view', to: 'dmsf_files#view', as: 'view_dmsf_file'
    get '/dmsf/files/:id', controller: 'dmsf_files', action: 'show', as: 'dmsf_file'
    delete '/dmsf/files/:id', controller: 'dmsf_files', action: 'delete'
    get '/dmsf/files/:id/restore', controller: 'dmsf_files', action: 'restore', as: 'restore_dmsf_file'
    get '/dmsf/files/:id/thumbnail', to: 'dmsf_files#thumbnail', as: 'dmsf_thumbnail'
    get '/dmsf/files/:id/:filename', to: 'dmsf_files#view', id: /\d+/, filename: /.*/, as: 'static_dmsf_file'

    # Approval workflow
    resources :dmsf_workflows do
      member do
        get 'autocomplete_for_user'
        get 'action'
        get 'assign'
        get 'log'
        post 'new_action'
        get 'start'
        post 'assignment'
        get 'new_step'
        put 'update_step'
        delete 'delete_step'
      end
    end

    post 'dmsf_workflows/:id/edit', controller: 'dmsf_workflows', action: 'add_step', id: /\d+/, via: :post
    delete 'dmsf_workflows/:id/edit', controller: 'dmsf_workflows', action: 'remove_step', id: /\d+/, via: :delete
    put 'dmsf_workflows/:id/edit', controller: 'dmsf_workflows', action: 'reorder_steps', id: /\d+/, via: :put

    # Links
    resources :dmsf_links do
      member do
        get 'restore'
        get 'autocomplete_for_project'
        get 'autocomplete_for_folder'
      end
    end

    # Public URLs
    resource :dmsf_public_urls

    # Folder permissions
    resource :dmsf_folder_permissions do
      member do
        get 'autocomplete_for_user'
        post 'append'
      end
    end

    # WebDAV workaround for clients checking WebDAV availability in the root
    unless Redmine::Plugin.installed?('easy_extensions')
      match '/',
            to: ->(env) { [405, {}, ["#{env['REQUEST_METHOD']} method is not allowed"]] },
            via: %i[propfind options]
    end
    match '/dmsf',
          to: ->(env) { [405, {}, ["#{env['REQUEST_METHOD']} method is not allowed"]] },
          via: %i[propfind options]
  end
end

redmine-plugins/redmine_dmsf/app/helpers/dmsf_helper.rb
# frozen_string_literal: true

# Redmine plugin for Document Management System "Features"
#
# Vít Jonáš <vit.jonas@gmail.com>, Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

require 'tmpdir'
require 'csv'

# DMSF helper
module DmsfHelper
  include Redmine::I18n

  unless Redmine::Plugin.installed?('easy_extensions')

    def late_javascript_tag(content_or_options_with_block = nil, html_options = {}, &block)
      javascript_tag content_or_options_with_block, html_options, &block
    end

  end

  def self.temp_filename(filename)
    filename = sanitize_filename(filename)
    timestamp = DateTime.current.strftime('%y%m%d%H%M%S')
    timestamp.succ! while Rails.root.join("tmp/#{timestamp}_#{filename}").exist?
    "#{timestamp}_#{filename}"
  end

  def self.sanitize_filename(filename)
    # Get only the filename, not the whole path
    just_filename = File.basename(filename.gsub('\\\\', '/'))
    # Replace all non alphanumeric, hyphens or periods with underscore
    just_filename.gsub!(/[^\w.\-]/, '_')
    # Keep the extension if any
    if !/^[a-zA-Z0-9_.\-]*$/.match?(just_filename) && just_filename =~ /(.[a-zA-Z0-9]+)$/
      extension = Regexp.last_match(1)
      just_filename = Digest::SHA256.hexdigest(just_filename) << extension
    end
    just_filename
  end

  def self.filetype_css(filename)
    extension = File.extname(filename)
    extension = extension[1, extension.length - 1]
    path = File.join(Redmine::Plugin.public_directory, ['redmine_dmsf', 'images', 'filetypes', "#{extension}.png"])
    cls = if File.exist?(path)
            +"filetype-#{extension}"
          else
            Redmine::MimeType.css_class_of filename
          end
    cls << ' dmsf-icon-file' if cls
    cls
  end

  def plugin_asset_path(plugin, asset_type, source)
    File.join('/plugin_assets', plugin.to_s, asset_type, source)
  end

  def render_principals_for_new_email(users)
    principals_check_box_tags 'user_ids[]', users
  end

  def webdav_url(project, folder)
    url = ["#{Setting.protocol}:/", Setting.host_name, 'dmsf', 'webdav']
    if project
      url << ERB::Util.url_encode(RedmineDmsf::Webdav::ProjectResource.create_project_name(project))
      if folder
        folders = []
        while folder
          folders << folder
          folder = folder.dmsf_folder
        end
        folders.reverse_each do |f|
          url << f.title
        end
      end
    end
    url << ''
    url.join '/'
  end
end

redmine-plugins/redmine_dmsf/app/views/dmsf/_add_email.html.erb
<%
  # Redmine plugin for Document Management System "Features"
  #
  # Karel Pičman <karel.picman@kontron.com>
  #
  # This program is free software; you can redistribute it and/or
  # modify it under the terms of the GNU General Public License
  # as published by the Free Software Foundation; either version 2
  # of the License, or (at your option) any later version.
  #
  # This program is distributed in the hope that it will be useful,
  # but WITHOUT ANY WARRANTY; without even the implied warranty of
  # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  # GNU General Public License for more details.
  #
  # You should have received a copy of the GNU General Public License
  # along with this program; if not, write to the Free Software
  # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<h3 class="title"><%= l(:label_email_address_add) %></h3>

<%= form_tag(append_email_dmsf_path(id: @project), remote: true, method: :post, id: 'new-user-form') do %>
  <%= hidden_field_tag :project_id, @project.id %>
  <p><%= label_tag 'user_search', l(:label_user_search) %><%= text_field_tag 'user_search', nil %></p>
  <%= late_javascript_tag "observeSearchfield('user_search', 'users_for_users', '#{ escape_javascript url_for(
    controller: 'dmsf', action: 'autocomplete_for_user') }')" %>
  <div id="users_for_watcher">
    <%= render_principals_for_new_email @principals %>
  </div>
  <p class="buttons">
    <%= submit_tag l(:button_add), name: nil, onclick: 'hideModal(this);' %>
    <%= submit_tag l(:button_cancel), name: nil, onclick: 'hideModal(this);', type: 'button' %>
  </p>
<% end %>

redmine-plugins/redmine_dmsf/app/views/dmsf/_main.html.erb
<%
  # Redmine plugin for Document Management System "Features"
  #
  # Vít Jonáš <vit.jonas@gmail.com>, Daniel Munn <dan.munn@munnster.co.uk>, Karel Pičman <karel.picman@kontron.com>
  #
  # This program is free software; you can redistribute it and/or
  # modify it under the terms of the GNU General Public License
  # as published by the Free Software Foundation; either version 2
  # of the License, or (at your option) any later version.
  #
  # This program is distributed in the hope that it will be useful,
  # but WITHOUT ANY WARRANTY; without even the implied warranty of
  # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  # GNU General Public License for more details.
  #
  # You should have received a copy of the GNU General Public License
  # along with this program; if not, write to the Free Software
  # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<% html_title l(:dmsf) %>
<% if @project %>
  <div class="contextual">
    <% unless @locked_for_user || @system_folder %>
      <% if @file_manipulation_allowed %>
        <%= link_to l(:label_document_new), multi_dmsf_upload_path(id: @project, folder_id: @folder),
                    class: 'icon icon-add',
                    data: { cy: 'button__new-file--dmsf' } %>
      <% end %>
      <% if @folder_manipulation_allowed %>
        <%= link_to l(:link_create_folder),
                    new_dmsf_path(id: @project, parent_id: @folder),
                    class: 'icon icon-add',
                    data: { cy: 'button__create-folder--dmsf' } %>
      <% end %>
    <% end %>
    <% if defined?(EasyExtensions) %>
      <%= render partial: 'dmsf_context_menus/main', locals: {
          folder_manipulation_allowed: @folder_manipulation_allowed,
          system_folder: @system_folder,
          folder: @folder,
          project: @project,
          locked_for_user: @locked_for_user,
          file_manipulation_allowed: @file_manipulation_allowed,
          trash_enabled: @trash_enabled,
          notifications: @notifications } %>
    <% else %>
      <%= actions_dropdown do %>
        <%= render partial: 'dmsf_context_menus/main', locals: {
            folder_manipulation_allowed: @folder_manipulation_allowed,
            system_folder: @system_folder,
            folder: @folder,
            project: @project,
            locked_for_user: @locked_for_user,
            file_manipulation_allowed: @file_manipulation_allowed,
            trash_enabled: @trash_enabled,
            notifications: @notifications} %>
      <% end %>
    <% end %>
  </div>
<% end %>

<%= render partial: 'path', locals: { folder: @folder, filename: nil, title: nil } %>

<%= render partial: 'description' %>

<%= form_tag(@project ? dmsf_folder_path(id: @project, folder_id: @folder) : dmsf_index_path,
             method: :get, id: 'query_form', class: 'dmsf-query-form') do %>
  <%= hidden_field_tag('folder_id', @folder.id) if @folder %>
  <div id="dmsf-query-form">
    <%= render partial: 'queries/query_form' %>
  </div>
<% end %>
<% if @query.valid? %>
  <% if @dmsf_count == 0 %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render partial: 'query_list', locals: { query: @query, dmsf_pages: @dmsf_pages, folder: @folder } %>
    <span class="pagination"><%= pagination_links_full @dmsf_pages, @dmsf_count %></span>
  <% end %>
<% end %>

<%= context_menu %>

<% if !@folder&.system && (@project || Setting.plugin_redmine_dmsf['dmsf_webdav'].present?) %>
    <% other_formats_links do |f| %>
      <% if @project %>
        <%= f.link_to 'CSV', url: { action: :show, id: @project, folder_id: @folder, encoding: Encoding::UTF_8 } %>
      <% end %>
      <% if Setting.plugin_redmine_dmsf['dmsf_webdav'].present? %>
        <span>
          <%= link_to 'WebDAV', webdav_url(@project, @folder), class: 'webdav' %>
        </span>
      <% end %>
    <% end %>
<% end %>

<% content_for :sidebar do %>
  <%= render partial: 'dmsf/sidebar' %>

  <% project_or_folder = @folder? @folder : @project %>
  <% if project_or_folder&.watchers.present? && User.current.allowed_to?(:view_dmsf_folder_watchers, @project) %>
    <div id="watchers">
      <%= render partial: 'watchers/watchers', locals: { watched: @folder ? @folder : @project } %>
    </div>
  <% end %>
<% end %>

<% if Redmine::Plugin.installed?('easy_extensions') %>
  <%= late_javascript_tag do %>
    $(function() {
      $("p.buttons").addClass("filter-buttons form-actions");
      let buttonApply = $("p.filter-buttons > a.icon-checked");
      buttonApply.addClass("button-positive");
      buttonApply.text("<%= l('easy_query.button_apply.issue') %>");
      let buttonClear = $("p.filter-buttons > a.icon-reload");
      buttonClear.addClass("button-negative");
      buttonClear.text("<%= l('easy_query.label.default_filters') %>");
      $("p.filter-buttons > a.icon-save").addClass("button");
      $("p.filter-buttons > a.icon-edit").addClass("button");
      $("p.filter-buttons > a.icon-del").addClass("button");
      $("#query_form_with_buttons > p.buttons").show();
    });
  <% end %>
<% end %>

<% late_javascript_tag do %>
  "$('#ajax-indicator').hide();"
<% end %>

redmine-plugins/redmine_dmsf/app/views/dmsf/copymove.html.erb
<%
  # Redmine plugin for Document Management System "Features"
  #
  # Vít Jonáš <vit.jonas@gmail.com>, Daniel Munn  <dan.munn@munnster.co.uk>, Karel Pičman <karel.picman@kontron.com>
  #
  # This program is free software; you can redistribute it and/or
  # modify it under the terms of the GNU General Public License
  # as published by the Free Software Foundation; either version 2
  # of the License, or (at your option) any later version.
  #
  # This program is distributed in the hope that it will be useful,
  # but WITHOUT ANY WARRANTY; without even the implied warranty of
  # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  # GNU General Public License for more details.
  #
  # You should have received a copy of the GNU General Public License
  # along with this program; if not, write to the Free Software
  # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<%= render partial: '/dmsf/path', locals: { folder: @folder, filename: nil, title: nil } %>

<% if @projects.present? || @fast_links %>
  <%= form_tag(entries_operations_dmsf_path, id: 'copyForm') do %>
    <% @ids.each do |id| %>
      <%= hidden_field_tag 'ids[]', id %>
    <% end %>
    <%= hidden_field_tag 'back_url', @back_url %>
    <%= hidden_field_tag 'id', @project %>
    <%= hidden_field_tag 'copy_entries', true %>
    <div class="box tabular">
      <% unless @fast_links %>
        <p>
          <%= label_tag 'dmsf_entries[target_project_id]', l(:field_target_project) %>
          <%= select_tag 'dmsf_entries[target_project_id]',
                         project_tree_options_for_select(@projects, selected: @target_project) %>
        </p>
      <% end %>
      <p>
        <%= label_tag 'dmsf_entries[target_folder_id]', l(:field_target_folder) %><%= ' #' if @fast_links %>
        <% if @fast_links %>
          <%= text_field_tag 'dmsf_entries[target_folder_id]', '', required: true, max_length: 255 %>
        <% else %>
          <%= select_tag 'dmsf_entries[target_folder_id]', options_for_select(@folders, selected: @target_folder&.id) %>
        <% end %>
      </p>
    </div>
    <p>
      <%= submit_tag l(:button_copy), id: 'copy_button', data: { cy: "button__copy--dmsf" } %>
      <%# TODO: Lock and proper permissions %>
      <% if User.current.allowed_to?(:folder_manipulation, @project) &&
        User.current.allowed_to?(:file_manipulation, @project) %>
        <%= submit_tag l(:button_move), id: 'move_button', data: { cy: "button__move--dmsf" } %>
      <% end %>
    </p>
  <% end %>
<% end %>

<%= late_javascript_tag do %>
  $('#move_button').click(function(event) {
    $('#copyForm').attr('action', "<%= entries_operations_dmsf_path(ids: @ids, move_entries: true) %>");
    $('#copyForm').submit();
  });
  <% unless @fast_links %>
    $('#dmsf_entries_target_project_id').change(function () {
      $('#content').load("<%= copymove_entries_path(id: @project, folder_id: @folder, ids: @ids) %>",
                          $('#copyForm').serialize());
    });
    $('#dmsf_entries_target_project_id').select2();
    $('#dmsf_entries_target_folder_id').select2();
  <% end %>
<% end %>

redmine-plugins/redmine_dmsf/app/views/dmsf/email_entries.html.erb
<%
  # Redmine plugin for Document Management System "Features"
  #
  # Vít Jonáš <vit.jonas@gmail.com>, Daniel Munn <dan.munn@munnster.co.uk>, Karel Pičman <karel.picman@kontron.com>
  #
  # This program is free software; you can redistribute it and/or
  # modify it under the terms of the GNU General Public License
  # as published by the Free Software Foundation; either version 2
  # of the License, or (at your option) any later version.
  #
  # This program is distributed in the hope that it will be useful,
  # but WITHOUT ANY WARRANTY; without even the implied warranty of
  # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  # GNU General Public License for more details.
  #
  # You should have received a copy of the GNU General Public License
  # along with this program; if not, write to the Free Software
  # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<% html_title l(:dmsf) %>

<%= render partial: 'path', locals: { folder: @folder, filename: nil, title: l(:heading_send_documents_by_email) } %>

<%= form_tag(email_entries_path(id: @project, folder_id: @folder), { method: :post }) do %>
  <%= hidden_field_tag 'email[zipped_content]', @email_params[:zipped_content] %>
  <%= hidden_field_tag 'email[folders]', @email_params[:folders].to_json %>
  <%= hidden_field_tag 'email[files]', @email_params[:files].to_json %>
  <%= hidden_field_tag 'email[from]', @email_params[:from] %>
  <%= hidden_field_tag 'email[reply_to]', @email_params[:reply_to] %>
  <%= hidden_field_tag 'back_url', @back_url %>
  <div class="box tabular">
    <p>
      <%= label_tag '', l(:label_email_from) %>
      <%= text_field_tag 'email[from_disabled]', @email_params[:from], class: 'dmsf-full-width', disabled: true %>
    </p>
    <p>
      <%= label_tag 'email[to]', l(:label_email_to) %>
      <span>
        <%= text_field_tag 'email[to]', @email_params[:to], class: 'dmsf-full-width', required: true %>
        <%= link_to l(:button_add), add_email_dmsf_path(id: @project),
          title: l(:label_email_address_add), class: 'icon icon-add', remote: true %>
      </span>
    </p>
    <p>
      <%= label_tag 'email[cc]', l(:label_email_cc) %>
      <%= text_field_tag 'email[cc]', @email_params[:cc], class: 'dmsf-full-width' %>
    </p>
    <p>
      <%= label_tag 'email[subject]', l(:label_email_subject) %>
      <%= text_field_tag 'email[subject]', @email_params[:subject], class: 'dmsf-full-width' %>
    </p>
    <p>
      <%= label_tag '', l(:label_email_documents) %>
      <span>
        <%= link_to 'Documents.zip', download_email_entries_path(id: @project, folder_id: @folder,
                                                                 path: @email_params[:zipped_content]) %>
        <%= l(:label_or) %>
        <%= check_box_tag('email[links_only]', 1, Setting.plugin_redmine_dmsf['dmsf_documents_email_links_only'],
              onchange: "$('#public_url').toggle($('#email_links_only').prop('checked'))")
        %>
        <%= l(:label_links_only) %>
        <%= render partial: 'dmsf_public_urls/new' %>
      </span>
    </p>
    <p>
      <%= label_tag 'email[body]', l(:label_email_body) %>
      <%= text_area_tag 'email[body]', @email_params['body'], rows: '20', class: 'dmsf-full-width wiki-edit' %>
    </p>
    <div class="form-actions">
      <%= submit_tag l(:label_email_send), class: 'button-positive' %>
    </div>
  </div>
<% end %>

<%= wikitoolbar_for 'email_body' %>